### ISSUE TITLE
Minimum Frequency is 20seconds?

### ISSUE THREAD

**Issue by FreshAF123** [traccar/traccar-client-android#369]
Im currently running android 7.0.0 using version 5.1.1 of traccar which is using the mapzen lost api for location updates and my minimum frequency i can send my location is 20s. Is this because of the api?

**Comment by tananaev** [comment]
There is no such version of Traccar Client.

**Comment by FreshAF123** [comment]
@tananaev sorry i was talking about v5.11

**Comment by tananaev** [comment]
It might be the limitation of system location provider.

**Comment by oliv3** [comment]
Well I had exactly the same problem, hence https://github.com/traccar/traccar-client-android/pull/347.
This was not just a cosmetic change, but a way to see what the behaviour was without having to check at logs.
I set update frequency to 1 second and indeed saw 20 seconds updates.
But only displaying HH:MM was of course not enough to confirm this.
So I think this is/was a Lost issue: it is gone since Lost removal.

**Comment by oliv3** [comment]
@FreshAF123 Time to upgrade.

**Comment by FreshAF123** [comment]
@oliv3 so after the removal of Lost in the later versions, the problem hence since not happen?

**Comment by oliv3** [comment]
Yes.
