### ISSUE TITLE
Location update delay

### ISSUE THREAD

**Issue by FreshAF123** [traccar/traccar-client-android#375]
![screenshot_20181005-153501 1](https://user-images.githubusercontent.com/43231504/46522167-9ee0c800-c8b4-11e8-87be-1dd73ce6710d.png)

i am using version 5.13 for android, frequency 30 distance 0 angle 0, for the first location update to the second location update, it updates later then 30s but for subsequent updates it maintains at 30s at every interval? i cant seem to understand why, isit the device issue or some software issue

**Comment by tananaev** [comment]
It might be a limitation of location provider.

**Comment by FreshAF123** [comment]
are u referring to the android's location api or to the GPS/wifi

**Comment by tananaev** [comment]
Android API.

**Comment by oliv3** [comment]
There are no limitations whatsoever.

@FreshAF123 The "interval" setting does exactly what it says: it allows you to set a _minimum_ interval between location updates.
In no way this guarantees an _exact_ time between updates.
So if you set it to 30 seconds, you are guaranteed you'll never receive updates in less than that time (e.g., 29 seconds).
But you are also _not guaranteed_ you'll receive updates every 30 seconds exactly.
This depends on the device moving (or not), and/or the [LoS](https://en.wikipedia.org/wiki/Line-of-sight_propagation).
The delay you observe for the first update is that, for some reason, your device is slow to get a GPS fix.
This is known as the [TTFF](https://en.wikipedia.org/wiki/Time_to_first_fix) interval.

Hope this makes things clearer now: try setting interval to 1 second, you'll get updates every second, most of the time. But sometimes, you might see a 2 seconds (or more, but not that much more) delay.

@tananaev I think documentation deserves an update, because 99% of the users think it's an _exact_ interval, rather than a _minimum_ interval.

**Comment by tananaev** [comment]
Documentation does say it's a minimum, but most of the time Android will respect the value and return at exact intervals.

**Comment by oliv3** [comment]
> most of the time

Sure, but if it doesn't, then you get **twice** the time.

**Comment by oliv3** [comment]
@tananaev One way to achieve exact updates, again signal theory, would be to call ```locationManager.requestLocationUpdates``` with _half_ the set interval ([Nyquist](https://en.wikipedia.org/wiki/Nyquist_frequency)).

**Comment by FreshAF123** [comment]
@oliv3 yes, that was exactly the scenario that happened to me, 30,30,30,30 and then suddenly 60, thanks so much for the comprehensive explanation!

**Comment by FreshAF123** [comment]
> There are no limitations whatsoever.
> 
> @FreshAF123 The "interval" setting does exactly what it says: it allows you to set a _minimum_ interval between location updates.
> In no way this guarantees an _exact_ time between updates.
> So if you set it to 30 seconds, you are guaranteed you'll never receive updates in less than that time (e.g., 29 seconds).
> But you are also _not guaranteed_ you'll receive updates every 30 seconds _exactly_.
> This depends on the device moving (or not), and/or the [LoS](https://en.wikipedia.org/wiki/Line-of-sight_propagation).
> The delay you observe for the first update is that, for some reason, your device is slow to get a GPS fix.
> This is known as the [TTFF](https://en.wikipedia.org/wiki/Time_to_first_fix) interval.
> 
> Hope this makes things clearer now: try setting interval to 1 second, you'll get updates every second, most of the time. But sometimes, you might see a 2 seconds delay.
> 
> Now this is fine for 1 second intervals, but in case you set a bigger interval and that you happen to miss a fix, update will happen at twice the interval time. So for 30 seconds, you may get updates at _43_ (TTFF, incompressible) seconds, then 30, 30, 30, 30, 30, _60_, 30, 30, _60_, 30, 30, 30, 30, ...
> This is signal theory.
> 
> @tananaev I think documentation deserves an update, because 99% of the users think it's an _exact_ interval, rather than a _minimum_ interval.

am i able to force  send a empty location update still even if i happen to miss at fix?
